### ISSUE TITLE
MySQLDumper :: SQL-Browser "Columns" reading bug

### ISSUE THREAD

**Issue by Loopshape** [DSB/MySQLDumper#10]
Hello, when I'm browsing some tables, the "SQL Browser" is showing some wrong table constellations. So I can't read the data statements inside a table when opening with the SQL-Browser of MySQLDumper.

**Comment by nifrz** [comment]
**Ich habe das selbe Problem:** 
Innerhalb einer Tabelle im SQL-Browser werden in den Zeilen in jedem Feld der Inhalt des ersten Feldes der jeweiligen Zeile angezeigt. 

Ich bin von PHP 5.6 auf 7 umgestiegen und habe die aktuelle Version des Dumpers hier von Github benutzt. Seitdem gibt es die Darstellungsfehler.

Ich würde mich freuen, wenn das gefixt werden könnte, da der SQL-Browser sehr praktisch und schnell ist.

**Comment by DSB** [comment]
Is this fixed with the latest commit?

**Comment by Loopshape** [comment]
@DSB 
Yes, the SQL-Browser shows correctly the tablenames and the related content of each column now. Thank you very much for fixing this annoying bug. This topic can be closed.
