### ISSUE TITLE
Uncaught Error: Call to undefined function ereg()

### ISSUE THREAD

**Issue by Andyt8** [DSB/MySQLDumper#11]
I tried newest MySQLDumper from Github because of PHP7. After updating of all files, I started a test. The backup or restore worked without problems. However, I found a problem if I want to delete a backup file.

`Uncaught Error: Call to undefined function ereg() in \msd\inc\functions.php:89
Stack trace:
#0 \msd\filemanagement.php(201): DeleteFilesM('work/backup/', 'database_2016...')
#1 {main}

  thrown in \msd\inc\functions.php on line 89`

Please for help or fix.

**Comment by partnerwerk** [comment]
Replace line 89 in /inc/functions.php with this:
`if (is_file($dir . $file) && preg_match("/^" . $pattern . "$/", $file)) {`

**Comment by Andyt8** [comment]
Thank you for the help. It was able to fix it.

**Comment by Croydon** [comment]
A pull request would actually solve the problem :)

**Comment by DSB** [comment]
Since no pull request dropped in I pushed this change to the repository. Thanks to @partnerwerk to post the solution.

**Comment by DSB** [comment]
But to state it clearly: open source lives from forking the repo, changing code in the fork and then create a pull request back to the original repository, so that this change can easily be added.

**Comment by Andyt8** [comment]
I'm on travel with poor internet connection. Additional at the moment I don't know what is a pull request, but hey something which will be learned after returning at home.
