### ISSUE TITLE
UTF8 - BIN

### ISSUE THREAD

**Issue by gtbu** [DSB/MySQLDumper#26]
When i make a backup then i have the choice between several versions like UTF-8 UTF-16 etc. When i install Mediawiki (like 1.27.4)  i can choose between bin and UTF-8 . What must i do to get the original 'BIN'
which is recommended.

**Comment by DSB** [comment]
It is better to select a charset that is in a defined state. Binary is something like "it is up to you dear client how to interprete the chars". So I would jump onto the utf-8 selection. MediaWiki is a PHP script and since PHP can't handle UTF-16 up to now, this wouldn't make sense to me.
