### ISSUE TITLE
Max execution time

### ISSUE THREAD

**Issue by gtbu** [DSB/MySQLDumper#28]
I am working with Mysqlumper master under xampp php7.025
When restoring a database of 835 MB (generated at strato with by phpmyadmin ) i get after some minutes the error 
Fatal error: Maximum execution time of 30 seconds exceeded in L:\xammp7025\htdocs\Dumper\restore.php on line 131 - change of 100-10000 to 5000-20000 has no effect.

**Comment by Galixte** [comment]
@gtbu you have to increase the value “max execution time” of PHP (usually in php.ini file) from XAMPP server.

**Comment by gtbu** [comment]
I have put the time to 30 minutes and no effect. My provider strato does not allow to download from an online installation of mysqldumper inspite of a green 'database connected' line in mysqldumper (neither remote) . 
The ony tool which allowed offline restore of my big database  on xampp was mysql maestro which i cannot install online - but maybe it will have the same problem as above. I think i will use sqldumpsplitter 2 and zip the splitted files and the use phpmayadmin to import them one after another  into an empty online database.

**Comment by DSB** [comment]
> change of 100-10000 to 5000-20000 has no effect.

You need to lower the number of executed sql commands per page call - not raise it.
Change to 50 - 1000 and retry.

2nd solution is to install MySQLDumper at Strato and create a new backup using the multipart feature which splits the dump automatically into several files.
