### ISSUE TITLE
Delete backups of deleted databases? Or sort by "last backup"?

### ISSUE THREAD

**Issue by Stryker93** [DSB/MySQLDumper#33]
I often delete databases and I am wondering if there is a feature to delete the backups of old, deleted databases, because I also do not need the backups anymore.

Alternativly I tried to click on the table header "Last Backup" (german: "letztes Backup") in the overview of all backups/databases, but there is no sort function for this table, when clicking on the table header.
Otherwise I could relativly fast delete the old backups manually.

**Comment by DSB** [comment]
In Configuration / Autodelete you can set the max number of backups you want to keep per database. Backups of deleted databases are not deleted. This needs to be done manually. But maybe one day you will be happy if you delete a database by accident and then find a backup inside the Dumper. ;)
