### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by gitFrank** [DSB/MySQLDumper#4]
Hi, with PHP7 and the latest version from here the install ends on Step 2.
Title Step 2 is visible, nothing else.

Can somebody confirm?

**Comment by michaelfm** [comment]
Noticed the same behavior. I resolved it by renaming **config.default.php** to **config.php**

**Comment by gitFrank** [comment]
Thanks, that was easy and works. 
Had created before a empty config.php but nothing happens, than i wrote here.

Now, every table (in the SQL-Browser) shows columns with the same column-title and content of the first column.

**Comment by DSB** [comment]
I renamed config.default.php back to config.php (how it was before an external merge). So this issue is gone.
